### ISSUE TITLE
python313Packages.pip fails to install on MacOS

### ISSUE THREAD

**Issue by ineiti** [jetify-com/devbox#2423]
### What happened?

I cannot install pip on a fresh devbox installation

### Steps to reproduce

1. devbox init
2. devbox add python313Packages.pip

### Command

add

### devbox.json

```jsonc
{
    "$schema": "https://raw.githubusercontent.com/jetify-com/devbox/0.13.6/.schema/devbox.schema.json",
    "packages": [],
    "shell": {
      "init_hook": [
        "echo 'Welcome to devbox!' > /dev/null"
      ],
      "scripts": {
        "test": [
          "echo \"Error: no test specified\" && exit 1"
        ]
      }
    }
  }
}
```

### Devbox version

0.13.6

### Nix version

nix (Nix) 2.23.3

### What system does this bug occur on?

macOS (Apple Silicon)

### Debug logs

DEVBOX_DEBUG=1 devbox add python313Packages.pip
time=2024-11-28T12:32:41.572+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:125 msg="searching for config file (including parent directories)" path=.
time=2024-11-28T12:32:41.573+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg="trying config file" path=devbox.json
time=2024-11-28T12:32:41.573+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:133 msg="config file found" path=/Users/ligasser/Programming/ineiti/fledger/flmodules/devbox.json dur=2.582375ms
time=2024-11-28T12:32:41.573+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:125 msg="searching for config file (including parent directories)" path=.
time=2024-11-28T12:32:41.573+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg="trying config file" path=devbox.json
time=2024-11-28T12:32:41.573+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:133 msg="config file found" path=/Users/ligasser/Programming/ineiti/fledger/flmodules/devbox.json dur=80.458µs
time=2024-11-28T12:32:41.613+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/nix.go:342 msg="nix --version --debug output" out="nix (Nix) 2.23.3\nSystem type: aarch64-darwin\nAdditional system types: \nFeatures: gc, signed-caches\nSystem configuration file: /etc/nix/nix.conf\nUser configuration files: /Users/ligasser/.config/nix/nix.conf:/etc/xdg/nix/nix.conf\nStore directory: /nix/store\nState directory: /nix/var/nix\nData directory: /nix/store/kcjwh67xvb3kkjp16p8nn0krzvanp3rl-nix-2.23.3/share\n"
time=2024-11-28T12:32:41.614+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:60 msg="nix command starting" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' eval --impure --raw --expr builtins.currentSystem" cmd.path=/nix/var/nix/profiles/default/bin/nix
time=2024-11-28T12:32:41.643+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:67 msg="nix command exited" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' eval --impure --raw --expr builtins.currentSystem" cmd.path=/nix/var/nix/profiles/default/bin/nix cmd.pid=70339 cmd.code=0 cmd.dur=29.225916ms
time=2024-11-28T12:32:41.643+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:125 msg="searching for config file (including parent directories)" path=.
time=2024-11-28T12:32:41.643+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg="trying config file" path=devbox.json
time=2024-11-28T12:32:41.644+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:133 msg="config file found" path=/Users/ligasser/Programming/ineiti/fledger/flmodules/devbox.json dur=122.708µs
time=2024-11-28T12:32:41.644+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=python313Packages.pip mode=auto
time=2024-11-28T12:32:41.644+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=python313Packages.pip mode=auto
time=2024-11-28T12:32:41.844+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:60 msg="nix command starting" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' search 'github:NixOS/nixpkgs/75a52265bda7fd25e06e3a67dee3f0354e73243c#python313Packages.pip' ^ --json" cmd.path=/nix/var/nix/profiles/default/bin/nix
time=2024-11-28T12:32:41.912+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:67 msg="nix command exited" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' search 'github:NixOS/nixpkgs/75a52265bda7fd25e06e3a67dee3f0354e73243c#python313Packages.pip' ^ --json" cmd.path=/nix/var/nix/profiles/default/bin/nix cmd.pid=70341 cmd.code=0 cmd.dur=68.391166ms
Info: Adding package "python313Packages.pip" to devbox.json
time=2024-11-28T12:32:41.913+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=python313Packages.pip mode=auto
time=2024-11-28T12:32:41.913+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=python313Packages.pip mode=auto
time=2024-11-28T12:32:41.913+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=python313Packages.pip mode=auto
time=2024-11-28T12:32:41.913+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:60 msg="nix command starting" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' path-info 'github:NixOS/nixpkgs/75a52265bda7fd25e06e3a67dee3f0354e73243c#python313Packages.pip' --json --impure" cmd.path=/nix/var/nix/profiles/default/bin/nix
time=2024-11-28T12:32:44.538+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:67 msg="nix command exited" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' path-info 'github:NixOS/nixpkgs/75a52265bda7fd25e06e3a67dee3f0354e73243c#python313Packages.pip' --json --impure" cmd.path=/nix/var/nix/profiles/default/bin/nix cmd.pid=70344 cmd.code=0 cmd.dur=2.624346959s
time=2024-11-28T12:32:44.538+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:60 msg="nix command starting" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' path-info --offline --json /nix/store/2igaqf2srcpj4l81yvbq8cb39vs44a0r-python3.13-pip-23.2.1 /nix/store/zdml7bwyirfcwxz1z8d7g62zqf4x32zq-python3.13-pip-23.2.1-man" cmd.path=/nix/var/nix/profiles/default/bin/nix
time=2024-11-28T12:32:44.611+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:67 msg="nix command exited" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' path-info --offline --json /nix/store/2igaqf2srcpj4l81yvbq8cb39vs44a0r-python3.13-pip-23.2.1 /nix/store/zdml7bwyirfcwxz1z8d7g62zqf4x32zq-python3.13-pip-23.2.1-man" cmd.path=/nix/var/nix/profiles/default/bin/nix cmd.pid=70350 cmd.code=0 cmd.dur=73.12075ms
Info: Installing the following packages to the nix store: python313Packages.pip
time=2024-11-28T12:32:44.617+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:73 msg="nix command starting" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' build --impure --no-link 'github:NixOS/nixpkgs/75a52265bda7fd25e06e3a67dee3f0354e73243c#python313Packages.pip'" cmd.path=/nix/var/nix/profiles/default/bin/nix
error: builder for '/nix/store/0n9m59j0wizskg7pnhgvc401ymbckm2x-python3.13-bootstrap-installer-0.7.0.drv' failed with exit code 1;
       last 25 log lines:
       > source root is source
       > patching sources
       > updateAutotoolsGnuConfigScriptsPhase
       > configuring
       > no configure script, doing nothing
       > building
       > Building wheel from /private/tmp/nix-build-python3.13-bootstrap-installer-0.7.0.drv-0/source
       > /nix/store/7s11wpz6zfdv6an14b0inz8lfbrn7j2a-python3.13-bootstrap-flit-core-3.9.0/lib/python3.13/site-packages/flit_core/wheel.py:45: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
       >   d = datetime.utcfromtimestamp(int(os.environ['SOURCE_DATE_EPOCH']))
       > Wheel built /private/tmp/nix-build-python3.13-bootstrap-installer-0.7.0.drv-0/source/dist/installer-0.7.0-py3-none-any.whl
       > installing
       > Traceback (most recent call last):
       >   File "<frozen runpy>", line 189, in _run_module_as_main
       >   File "<frozen runpy>", line 148, in _get_module_details
       >   File "<frozen runpy>", line 112, in _get_module_details
       >   File "/private/tmp/nix-build-python3.13-bootstrap-installer-0.7.0.drv-0/source/src/installer/__init__.py", line 6, in <module>
       >     from installer._core import install  # noqa
       >     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   File "/private/tmp/nix-build-python3.13-bootstrap-installer-0.7.0.drv-0/source/src/installer/_core.py", line 7, in <module>
       >     from installer.destinations import WheelDestination
       >   File "/private/tmp/nix-build-python3.13-bootstrap-installer-0.7.0.drv-0/source/src/installer/destinations.py", line 19, in <module>
       >     from installer.scripts import Script
       >   File "/private/tmp/nix-build-python3.13-bootstrap-installer-0.7.0.drv-0/source/src/installer/scripts.py", line 6, in <module>
       >     from importlib.resources import read_binary
       > ImportError: cannot import name 'read_binary' from 'importlib.resources' (/nix/store/zg0grp8rj64c37m4c7nazva4g45dqc2p-python3-3.13.0a1/lib/python3.13/importlib/resources/__init__.py)
       For full logs, run 'nix log /nix/store/0n9m59j0wizskg7pnhgvc401ymbckm2x-python3.13-bootstrap-installer-0.7.0.drv'.
error: 1 dependencies of derivation '/nix/store/wlgsyzmnjdbr3h1z2nk2b4jx127k3zs7-pypa-install-hook.drv' failed to build
error: 1 dependencies of derivation '/nix/store/c2gny0nfybpbqmdk94z4f8hy0r0ayj1a-python3.13-bootstrap-build-1.0.3.drv' failed to build
error: 1 dependencies of derivation '/nix/store/dma78bkkrqq6fsi7kafhzg1m7fhh126i-pypa-build-hook.sh.drv' failed to build
error: 1 dependencies of derivation '/nix/store/f2jdy0qjaagd2kp0pmw27qiqs5akwdqq-python3.13-flit-core-3.9.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/zwhcrjf28kxydapl02wnib2wc5jxz4iv-python3.13-installer-0.7.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/bah5fy2dz220b58ix0bbcmjah0n7rnb1-pypa-install-hook.drv' failed to build
error: 1 dependencies of derivation '/nix/store/zvfakp87j8k97gfkn39hxzr951lv6qcs-python3.13-build-1.0.3.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8ilh81y30kd9ml1frmjikzd4m2zrxbvc-python3.13-wheel-0.41.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/g0als7rrkac94hz0iaw8r4d3g1vasrr7-python3.13-pip-23.2.1.drv' failed to build
time=2024-11-28T12:32:47.690+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:80 msg="nix command exited" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' build --impure --no-link 'github:NixOS/nixpkgs/75a52265bda7fd25e06e3a67dee3f0354e73243c#python313Packages.pip'" cmd.path=/nix/var/nix/profiles/default/bin/nix cmd.pid=70356 cmd.code=1 cmd.dur=3.073235084s

Error: There was an error installing nix packages
source: nix: command error: nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' build --impure --no-link 'github:NixOS/nixpkgs/75a52265bda7fd25e06e3a67dee3f0354e73243c#python313Packages.pip': exit code 1

time=2024-11-28T12:32:47.690+01:00 level=ERROR source=go.jetpack.io/devbox/internal/boxcli/midcobra/debug.go:68 msg="command error" stderr="" execid=d359140272ad43588e49e541893e4251 stack=<nil>
time=2024-11-28T12:32:47.691+01:00 level=ERROR source=go.jetpack.io/devbox/internal/boxcli/midcobra/debug.go:70 msg="command error" execid=d359140272ad43588e49e541893e4251 stack=<nil>
time=2024-11-28T12:32:47.691+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:125 msg="searching for config file (including parent directories)" path=.
time=2024-11-28T12:32:47.691+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg="trying config file" path=devbox.json
time=2024-11-28T12:32:47.692+01:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:133 msg="config file found" path=/Users/ligasser/Programming/ineiti/fledger/flmodules/devbox.json dur=495.125µs

**Comment by javapapo** [comment]
+1
